#!/usr/bin/env python3
"""Regenerate ``abax/core/_funcmeta_generated.py`` from the formula reference.

``docs/formula-reference.md`` documents every built-in function in Markdown
tables whose first two columns are ``Function`` and ``Description``. This
script harvests those NAME -> one-line-description pairs, normalizes them to
the style of the hand-written ``funcmeta.DESCRIPTIONS`` entries (no markdown
markup, sentence case, trailing period), filters them to names actually
present in the live registries, and writes the result as a generated module::

    py scripts/gen_funcmeta_descriptions.py

The output is deterministic (names sorted) so a rerun on an unchanged tree is
diff-clean. Rows it cannot render faithfully as plain one-line text (leftover
markdown artifacts, empty, or absurdly long) are skipped and reported on
stderr — the doc stays the single source of truth; nothing is invented here.

Hand-written entries in ``funcmeta.DESCRIPTIONS`` always take precedence over
the generated dict at lookup time; overlap is expected and harmless.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Allow running as a plain script (`py scripts/gen_funcmeta_descriptions.py`) —
# put the repo root on the path so `import abax` resolves regardless of cwd.
sys.path.insert(0, str(ROOT))

from abax.core.completion import function_names  # noqa: E402

DOC = ROOT / "docs" / "formula-reference.md"
OUT = ROOT / "abax" / "core" / "_funcmeta_generated.py"

HEADER = (
    "# AUTO-GENERATED by scripts/gen_funcmeta_descriptions.py — do not edit by hand;\n"
    "# hand-written entries in funcmeta.DESCRIPTIONS take precedence.\n"
)

# Split a table row on pipes that are not escaped (`\|` stays inside a cell).
_CELL_SPLIT = re.compile(r"(?<!\\)\|")
# A worksheet function name: SUM, LOG10, NORM.S.INV, R.DNORM, MODE.MULT, ...
_NAME_RE = re.compile(r"^[A-Z][A-Z0-9._]*$")
# Backtick-quoted tokens in the Function column (`DMAX` / `DMIN`, `X` · `Y`).
_TICKED = re.compile(r"`([^`]+)`")
# [text](target) markdown links -> text.
_LINK = re.compile(r"\[([^\]]*)\]\([^)]*\)")
# **bold** / *emphasis* -> bare text.
_BOLD = re.compile(r"\*\*([^*]+)\*\*")
_EMPH = re.compile(r"\*([^*]+)\*")
# Characters that mark an unrenderable leftover — skip the row instead of
# guessing at plain text (e.g. the literal `\|Γ\|` maths bars in the RF table).
_ARTIFACTS = ("*", "[", "]", "`", "|", "\\")

MAX_LEN = 200


def _split_cells(row: str) -> list[str]:
    """The stripped cell texts of a `| a | b |` table row."""
    cells = [c.strip() for c in _CELL_SPLIT.split(row)]
    # Leading and trailing `|` produce empty first/last fragments.
    if cells and cells[0] == "":
        cells = cells[1:]
    if cells and cells[-1] == "":
        cells = cells[:-1]
    return cells


def _names(cell: str) -> list[str]:
    """Every function name in a Function-column cell, in row order."""
    return [t for t in _TICKED.findall(cell) if _NAME_RE.match(t)]


def _normalize(desc: str) -> str | None:
    """One clean plain-text line in DESCRIPTIONS style, or None to skip."""
    s = _LINK.sub(r"\1", desc)
    s = _BOLD.sub(r"\1", s)
    s = _EMPH.sub(r"\1", s)
    s = s.replace("`", "")
    s = s.replace(" * ", " × ")                # spaced multiplication, not emphasis
    s = " ".join(s.split())
    if not s or any(ch in s for ch in _ARTIFACTS):
        return None
    if len(s) > MAX_LEN:
        return None
    # Sentence case — but only when the first word is a plain lowercase word;
    # unit-style tokens like "dBm" or symbols like "λ" must keep their casing.
    first = s.split(" ", 1)[0]
    if re.fullmatch(r"[a-z][a-z0-9'’-]*", first):
        s = s[0].upper() + s[1:]
    if not s.endswith("."):
        s += "."
    return s


def harvest(text: str) -> tuple[dict[str, str], list[str]]:
    """``{NAME: description}`` from every Function/Description table, plus a
    list of skipped-row notes."""
    out: dict[str, str] = {}
    skipped: list[str] = []
    in_table = False
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("|"):
            in_table = False
            continue
        cells = _split_cells(stripped)
        if len(cells) >= 2 and cells[0] == "Function" and cells[1] == "Description":
            in_table = True
            continue
        if not in_table or len(cells) < 2:
            continue
        if set(cells[0]) <= {"-", " "}:                       # |---|---| separator
            continue
        names = _names(cells[0])
        if not names:
            continue
        desc = _normalize(cells[1])
        if desc is None:
            skipped.append(f"{'/'.join(names)}: {cells[1]!r}")
            continue
        for name in names:
            out.setdefault(name, desc)                        # first mention wins
    return out, skipped


def main() -> int:
    harvested, skipped = harvest(DOC.read_text(encoding="utf-8"))
    registered = set(function_names())
    unregistered = sorted(n for n in harvested if n not in registered)
    entries = {n: harvested[n] for n in sorted(harvested) if n in registered}

    lines = [
        HEADER,
        '"""One-line function descriptions harvested from docs/formula-reference.md.',
        "",
        "Regenerate with ``py scripts/gen_funcmeta_descriptions.py``. Pure stdlib —",
        "this module is data only.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "GENERATED_DESCRIPTIONS: dict[str, str] = {",
    ]
    lines += [f"    {name!r}: {desc!r}," for name, desc in entries.items()]
    lines += ["}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")

    print(f"harvested {len(harvested)} names from {DOC.name}; "
          f"wrote {len(entries)} registered entries to {OUT.relative_to(ROOT)}")
    if unregistered:
        print(f"skipped {len(unregistered)} documented-but-unregistered names: "
              + ", ".join(unregistered), file=sys.stderr)
    for note in skipped:
        print(f"skipped row (not plain text / too long): {note}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
